#!/bin/bash
#./ecl-test setup --excludeclass=3rdparty,embedded,spray --pq=10 --server 34.66.125.65

#./ecl-test setup --excludeclass=3rdparty,embedded,spray --pq=10 --server a95fcae1419214aa98d44d43b6b5a43d-1580568255.us-east-1.elb.amazonaws.com


# hpcc-dev-160
#server=a4375fcb07d314446b3036e4a5a3ded0-867327524.us-east-1.elb.amazonaws.com

#eks-hpcc-1

# eks-hpcc-1
#server=ab619426a27cf48cc8295221b53958ba-716284310.us-east-1.elb.amazonaws.com

#server="20.62.178.25"
server="localhost"


#ecl run thor -s ${server}  <ecl file path>
rm -rf ~/tmp/playground.out 
./test-playground.sh -d ~/tmp/HPCC-Platform -s $server -t "hthor roxie-workunit thor" | tee -a ~/tmp/playground.out 
